module: CredentialsHTTP
author: IBM
github_url: https://github.com/KituraKommunity/Kitura-CredentialsHTTP/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-CredentialsHTTP.xcodeproj, -target, CredentialsHTTP, LIBRARY_SEARCH_PATHS=.build/debug]

